spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=TransportBooking;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
fasttravel.app.jwtSecret=FastTravelSecretKey2026SuperSecureAndLongEnoughForHmacSha256_DoNotShare
fasttravel.app.jwtExpirationMs=86400000
vnpay.tmn-code=9E5TG919
vnpay.hash-secret=CKXLS9C9MYVELLDBJNXAESC7T20MJH3H
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/v1/payment/vnpay-return

